---
name: Karate Tests CI
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  karate-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: temurin
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Ejecutar pruebas Karate
        run: mvn clean test -Dtest=**/*Test.java
      - name: Subir reportes Karate
        uses: actions/upload-artifact@v4
        with:
          name: karate-reports
          path: target/karate-reports/
